from datetime import datetime

from pydantic import BaseModel, ConfigDict, EmailStr
from typing import Optional
# schemas.py is used to define how incoming and outgoing data should look.
# In FastAPI, we use Pydantic models to validate request bodies and to shape responses.
# This keeps the API clean and predictable.
#
# Example:
# - when someone sends a POST request, FastAPI checks that title/content/published exist and are valid
# - when we return data, FastAPI can convert database objects into JSON using these models


class PostBase(BaseModel):
    # This is the common structure for every post.
    # We keep fields that are used both while creating and returning posts.
    title: str
    content: str
    published: bool = True


class Postcreate(PostBase):
    # This model is used for creating a new post.
    # It inherits all fields from PostBase, so the client only needs to send:
    # title, content, and optionally published.
    # The class itself does not add anything extra.
    pass


class Post(PostBase):
    # This model is used when returning a post from the database.
    # It adds extra fields like id and content_at that are generated by the database.
    id: int
    content_at: datetime
    owner_id : int
    # from_attributes=True tells Pydantic to read values from an SQLAlchemy model object.
    # Without this, FastAPI may not be able to convert a database row (like models.Post)
    # into a JSON response automatically.
    model_config = ConfigDict(from_attributes=True)

class UserCreate(BaseModel):
    email: EmailStr
    password: str


class UserOut(BaseModel):
    id: int
    email: EmailStr
    content_at: datetime

    model_config = ConfigDict(from_attributes=True)


class UserLogin(BaseModel):
    email : EmailStr
    password : str


class Token(BaseModel):
    access_token : str
    token_type : str

class TokenData(BaseModel):
    id : Optional[int] = None